service: unravelService

provider:
  name: aws
  runtime: nodejs4.3



functions:
  get:
    handler: listings/get.get
    events:
      - http:
          path: listings
          method: get
          cors: true
