service: unravelService

provider:
  name: aws
  runtime: nodejs4.3



functions:
  getListings:
    handler: listings/get.get
    events:
      - http:
          path: listings
          method: get
          cors: true
  infoForListing:
    handler: listing/get.get
    events:
      - http:
          path: listings/{rid}
          method: get
          cors: true
